name: Elixir CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ngobrolin_test
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3

      - name: Set up Elixir
        uses: erlef/setup-elixir@v1.2.1
        with:
          elixir-version: '1.18'
          otp-version: '27.0'

      - name: Install Dependencies
        run: mix deps.get

      - name: Prepare DB
        run: mix ecto.create && mix ecto.migrate
        env:
          DATABASE_URL: "ecto://postgres:postgres@postgres:5432/ngobrolin_test"
          
      - name: Run Tests
        run: mix test
        env:
          DATABASE_URL: "ecto://postgres:postgres@postgres:5432/ngobrolin_test"
